import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, FileText, Loader2 } from "lucide-react";
import { api } from "@/lib/api";
import { CIOSummaryCard } from "@/components/CIOSummaryCard";
import { FundamentalsCard } from "@/components/FundamentalsCard";
import { QuantTechCard } from "@/components/QuantTechCard";
import { MacroCard } from "@/components/MacroCard";
import { MasterSynthesisCard } from "@/components/MasterSynthesisCard";
import { fmtPrice } from "@/lib/utils";
import { SignalBadge } from "@/components/SignalBadge";
import { MOCK_WATCHLIST } from "@/lib/api";

interface Props { symbol: string; }

export function ReportViewer({ symbol }: Props) {
  const { data: report, isLoading, isError } = useQuery({
    queryKey: ["report", symbol],
    queryFn: () => api.getReport(symbol),
    refetchInterval: api.POLL_MS,
  });

  const ticker = MOCK_WATCHLIST.find(t => t.symbol === symbol);

  if (isLoading) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center gap-4 text-muted-foreground">
        <Loader2 size={32} className="animate-spin text-accent" />
        <div className="text-center">
          <p className="font-sans text-sm font-semibold text-foreground">Generating analyst report...</p>
          <p className="font-sans text-xs text-muted-foreground">Running 5 specialist agents for {symbol}</p>
        </div>
      </div>
    );
  }

  if (isError || !report) {
    return (
      <div className="flex flex-1 flex-col items-center justify-center gap-4 text-muted-foreground">
        <AlertTriangle size={32} className="text-bear" />
        <div className="text-center">
          <p className="font-sans text-sm font-semibold text-foreground">No report available</p>
          <p className="font-sans text-xs text-muted-foreground">
            {symbol} is not in the mock dataset. Add it to MOCK_REPORTS in src/lib/api.ts
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-1 flex-col overflow-hidden">
      {/* Report header */}
      <div className="border-b border-border bg-hero px-8 py-6">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-3">
              <span className="font-mono text-3xl font-bold text-primary-foreground">{symbol}</span>
              <SignalBadge signal={ticker?.signal ?? "neutral"} label={report.exchange} size="sm" dot={false} />
            </div>
            <p className="mt-0.5 font-display text-lg font-medium text-primary-foreground/80">{report.company_name}</p>
            <p className="mt-1 font-sans text-xs text-primary-foreground/50">{report.sector}</p>
          </div>
          <div className="text-right">
            <p className="font-mono text-3xl font-bold text-primary-foreground">{fmtPrice(ticker?.price ?? 0)}</p>
            <p className={`mt-1 font-mono text-sm font-semibold ${(ticker?.change1d ?? 0) >= 0 ? "text-bull" : "text-bear"}`}>
              {(ticker?.change1d ?? 0) >= 0 ? "+" : ""}{ticker?.change1d?.toFixed(2)}% today
            </p>
            <div className="mt-2 flex items-center justify-end gap-2">
              <FileText size={11} className="text-primary-foreground/40" />
              <span className="font-sans text-[10px] text-primary-foreground/40 uppercase tracking-wider">Retail Intelligence Desk</span>
            </div>
          </div>
        </div>
      </div>

      {/* Scrollable report body */}
      <div className="flex-1 overflow-y-auto scrollbar-thin">
        <div className="mx-auto max-w-4xl space-y-6 px-8 py-7">
          <CIOSummaryCard data={report.cio} />
          <FundamentalsCard data={report.fundamentals} />
          <QuantTechCard data={report.quant} />
          <MacroCard data={report.macro} />
          <MasterSynthesisCard data={report.master} ticker={symbol} />

          {/* Report footer */}
          <div className="rounded-md border border-border bg-muted p-4 text-center">
            <p className="font-sans text-[11px] text-muted-foreground leading-relaxed">
              This report is generated by the <span className="font-semibold text-foreground">Retail Intelligence Desk</span> multi-agent system.
              All analysis is for research and screening purposes only — not investment advice.
              Data may be delayed or synthetic. Always verify with primary sources before making investment decisions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
